"use client";
/**
 * ItineraryTextExport — generates clean plain-text itinerary for copying/sharing
 */
import React, { useState } from "react";
import { Copy, Check, Printer, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDate, formatMinutes, CATEGORY_ICONS, formatPriceLevel } from "@/lib/utils";
import type { Trip, Place, ItineraryDay } from "@/lib/types";
import { downloadText } from "@/lib/utils";
import { toast } from "sonner";

interface ItineraryTextExportProps {
  trip: Trip;
  places: Place[];
  days: ItineraryDay[];
}

function buildText(trip: Trip, places: Place[], days: ItineraryDay[]): string {
  const placeMap = new Map(places.map(p => [p.id, p]));
  const lines: string[] = [];

  lines.push(`═══════════════════════════════════`);
  lines.push(`  ${trip.emoji ?? "✈️"} ${trip.name.toUpperCase()}`);
  if (trip.startDate && trip.endDate) {
    lines.push(`  ${formatDate(trip.startDate, "MMM d")} – ${formatDate(trip.endDate, "MMM d, yyyy")}`);
  }
  if (trip.notes) lines.push(`  ${trip.notes}`);
  lines.push(`═══════════════════════════════════`);
  lines.push("");

  for (const day of days) {
    const label = day.date.length === 10
      ? `DAY ${day.dayNumber} — ${formatDate(day.date, "EEEE, MMM d").toUpperCase()}`
      : `DAY ${day.dayNumber}`;

    lines.push(label);
    lines.push("─".repeat(label.length));

    if (day.theme) lines.push(`Theme: ${day.theme}`);
    lines.push("");

    for (const item of day.items) {
      const p = placeMap.get(item.placeId);
      if (!p) continue;

      const time = item.startTime ? `[${item.startTime}] ` : "";
      const icon = CATEGORY_ICONS[p.category];
      const dur  = formatMinutes(item.duration);
      const price = formatPriceLevel(p.priceLevel, trip.currency);
      const travel = item.travelTimeFromPrevious
        ? `  → ${formatMinutes(item.travelTimeFromPrevious)} walk/transit`
        : "";

      if (travel) lines.push(travel);
      lines.push(`${time}${icon} ${p.title}  (${dur} · ${price})`);

      if (p.neighborhood || p.city) {
        lines.push(`   📍 ${[p.neighborhood, p.city].filter(Boolean).join(", ")}`);
      }
      if (p.notes) {
        const shortNote = p.notes.slice(0, 120) + (p.notes.length > 120 ? "…" : "");
        lines.push(`   💬 ${shortNote}`);
      }
      if (p.sourceUrl) lines.push(`   🔗 ${p.sourceUrl}`);
      lines.push("");
    }

    const totalDur = day.items.reduce((s, i) => s + i.duration + (i.travelTimeFromPrevious ?? 0), 0);
    lines.push(`Total: ~${formatMinutes(totalDur)}`);
    lines.push("");
  }

  lines.push("─".repeat(35));
  lines.push(`Generated by NomadNote — designed by Henrique Ribeiro`);
  lines.push(`Private & local-first. No account needed.`);

  return lines.join("\n");
}

export function ItineraryTextExport({ trip, places, days }: ItineraryTextExportProps) {
  const [copied, setCopied] = useState(false);

  if (!days.length) return null;

  const text = buildText(trip, places, days);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      toast.success("Itinerary copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Couldn't copy — try the download button");
    }
  };

  const handleDownload = () => {
    downloadText(text, `${trip.name.toLowerCase().replace(/\s+/g, "-")}-itinerary.txt`);
    toast.success("Itinerary downloaded");
  };

  const handlePrint = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<html><head><title>${trip.name} Itinerary</title>
<style>
  body { font-family: "Courier New", monospace; font-size: 13px; line-height: 1.6; padding: 2cm; white-space: pre-wrap; }
  @media print { body { padding: 1cm; } }
</style>
</head><body>${text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}</body></html>`);
    win.document.close();
    win.print();
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <p className="text-sm font-medium text-muted-foreground">Export itinerary</p>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={handlePrint} className="gap-1.5">
            <Printer className="h-3.5 w-3.5" /> Print
          </Button>
          <Button size="sm" variant="outline" onClick={handleDownload} className="gap-1.5">
            <FileText className="h-3.5 w-3.5" /> .txt
          </Button>
          <Button size="sm" onClick={handleCopy} className="gap-1.5">
            {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied!" : "Copy"}
          </Button>
        </div>
      </div>

      <pre className="text-xs font-mono bg-muted/60 border border-border rounded-xl p-4 overflow-x-auto max-h-64 text-muted-foreground leading-relaxed">
        {text.slice(0, 800)}{text.length > 800 ? "\n…" : ""}
      </pre>
    </div>
  );
}
