/**
 * NomadNote — Demo Data
 * Two fully-populated sample trips to showcase the app on first load.
 */

import type { Trip, Place, Collection, PackingItem } from "./types";

const TS = Date.now();
const DAY = 86400000;

// ── DEMO TRIP 1: Tokyo ───────────────────────────────────────

export const DEMO_TRIP_TOKYO: Trip = {
  id: "demo-tokyo",
  name: "Tokyo Dream",
  description: "5 days exploring the best of Tokyo — from ancient temples to futuristic neighborhoods.",
  emoji: "🗼",
  startDate: "2025-04-10",
  endDate: "2025-04-14",
  timezone: "Asia/Tokyo",
  budgetStyle: "moderate",
  notes: "Check cherry blossom forecast. Get IC card at airport.",
  archived: false,
  itineraryMode: "balanced",
  itinerary: [
    {
      date: "2025-04-10",
      dayNumber: 1,
      theme: "Asakusa and food market warmup",
      notes: "Low-friction first day with one classic anchor and a food stop.",
      items: [
        { id: "demo-it-tokyo-1-1", placeId: "tp-sensoji", startTime: "09:00", endTime: "10:30", duration: 90, locked: true, travelTimeFromPrevious: 0, order: 0 },
        { id: "demo-it-tokyo-1-2", placeId: "tp-tsukiji", startTime: "12:00", endTime: "13:30", duration: 90, locked: false, travelTimeFromPrevious: 25, order: 1 },
      ],
    },
    {
      date: "2025-04-11",
      dayNumber: 2,
      theme: "Shibuya, Harajuku, and Meiji loop",
      notes: "Walkable west-side cluster with a clear rainy backup nearby.",
      items: [
        { id: "demo-it-tokyo-2-1", placeId: "tp-meiji", startTime: "10:00", endTime: "11:30", duration: 90, locked: false, travelTimeFromPrevious: 0, order: 0 },
        { id: "demo-it-tokyo-2-2", placeId: "tp-harajuku", startTime: "12:00", endTime: "13:15", duration: 75, locked: false, travelTimeFromPrevious: 12, order: 1 },
        { id: "demo-it-tokyo-2-3", placeId: "tp-shibuya", startTime: "15:00", endTime: "16:30", duration: 90, locked: true, travelTimeFromPrevious: 18, order: 2 },
      ],
    },
    {
      date: "2025-04-12",
      dayNumber: 3,
      theme: "Rain-friendly art day",
      notes: "Indoor anchor day for weather resilience.",
      items: [
        { id: "demo-it-tokyo-3-1", placeId: "tp-teamlab", startTime: "10:30", endTime: "12:30", duration: 120, locked: true, travelTimeFromPrevious: 0, order: 0 },
        { id: "demo-it-tokyo-3-2", placeId: "tp-ichiran", startTime: "18:30", endTime: "19:30", duration: 60, locked: false, travelTimeFromPrevious: 28, order: 1 },
      ],
    },
  ],
  currency: "JPY",
  createdAt: TS - 7 * DAY,
  updatedAt: TS - 1 * DAY,
};

export const DEMO_PLACES_TOKYO: Place[] = [
  {
    id: "tp-sensoji",
    title: "Senso-ji Temple",
    notes: "Arrive early to beat crowds. Buy omamori charms. Nakamise-dori shopping street leading up to it is great for souvenirs.",
    tags: ["must-see", "free", "historic", "morning"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Asakusa",
    latitude: 35.7148,
    longitude: 139.7967,
    category: "religious",
    priority: 1,
    priceLevel: "free",
    estimatedDurationMinutes: 90,
    bestTimeOfDay: "morning",
    indoorOutdoor: "outdoor",
    visited: true,
    favorite: true,
    isFree: true,
    isChildFriendly: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: ["demo-col-tokyo-must"],
    createdAt: TS - 6 * DAY,
    updatedAt: TS - 1 * DAY,
  },
  {
    id: "tp-tsukiji",
    title: "Tsukiji Outer Market",
    notes: "Best tamagoyaki in the world. Get there by 8am for the freshest seafood. Try the tuna sashimi bowls.",
    tags: ["food", "morning", "market", "must-eat"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Tsukiji",
    latitude: 35.6654,
    longitude: 139.7707,
    category: "market",
    priority: 1,
    priceLevel: "budget",
    estimatedDurationMinutes: 90,
    bestTimeOfDay: "morning",
    indoorOutdoor: "outdoor",
    visited: false,
    favorite: true,
    isFree: false,
    dietaryTags: ["seafood"],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: ["demo-col-tokyo-food"],
    createdAt: TS - 6 * DAY,
    updatedAt: TS - 6 * DAY,
  },
  {
    id: "tp-shibuya",
    title: "Shibuya Crossing",
    notes: "Go at rush hour (weekday 5-7pm) for maximum chaos. Great shot from Starbucks on the corner.",
    tags: ["iconic", "photography"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Shibuya",
    latitude: 35.6595,
    longitude: 139.7004,
    category: "attraction",
    priority: 1,
    priceLevel: "free",
    estimatedDurationMinutes: 30,
    bestTimeOfDay: "evening",
    indoorOutdoor: "outdoor",
    visited: false,
    favorite: true,
    isFree: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: ["demo-col-tokyo-must"],
    createdAt: TS - 5 * DAY,
    updatedAt: TS - 5 * DAY,
  },
  {
    id: "tp-teamlab",
    title: "teamLab Borderless",
    notes: "Book tickets WELL in advance. Allow 3+ hours. Spectacular digital art immersion.",
    tags: ["art", "indoor", "book-ahead"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Odaiba",
    latitude: 35.6236,
    longitude: 139.7750,
    category: "entertainment",
    priority: 2,
    priceLevel: "expensive",
    estimatedDurationMinutes: 180,
    bestTimeOfDay: "afternoon",
    indoorOutdoor: "indoor",
    visited: false,
    favorite: false,
    isFree: false,
    isDateNight: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: [],
    createdAt: TS - 5 * DAY,
    updatedAt: TS - 5 * DAY,
  },
  {
    id: "tp-shinjuku",
    title: "Shinjuku Gyoen Garden",
    notes: "Cherry blossoms mid-late March. Alcohol not allowed. Great escape from the city noise.",
    tags: ["park", "cherry-blossom", "relaxing"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Shinjuku",
    latitude: 35.6851,
    longitude: 139.7100,
    category: "park",
    priority: 2,
    priceLevel: "budget",
    estimatedDurationMinutes: 120,
    bestTimeOfDay: "afternoon",
    indoorOutdoor: "outdoor",
    visited: false,
    favorite: false,
    isFree: false,
    isChildFriendly: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: [],
    createdAt: TS - 4 * DAY,
    updatedAt: TS - 4 * DAY,
  },
  {
    id: "tp-ichiran",
    title: "Ichiran Ramen",
    notes: "Solo ramen booths. Order the 'original' with extra noodles. The Shibuya branch is closest.",
    tags: ["food", "ramen", "solo-friendly", "must-eat"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Shibuya",
    latitude: 35.6594,
    longitude: 139.6988,
    category: "restaurant",
    priority: 1,
    priceLevel: "budget",
    estimatedDurationMinutes: 45,
    bestTimeOfDay: "evening",
    indoorOutdoor: "indoor",
    visited: false,
    favorite: true,
    isFree: false,
    isSoloFriendly: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: ["demo-col-tokyo-food"],
    createdAt: TS - 4 * DAY,
    updatedAt: TS - 4 * DAY,
  },
  {
    id: "tp-meiji",
    title: "Meiji Shrine",
    notes: "Free entry. Adjacent Yoyogi Park is excellent for people watching on weekends.",
    tags: ["shrine", "peaceful", "free"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Harajuku",
    latitude: 35.6763,
    longitude: 139.6993,
    category: "religious",
    priority: 2,
    priceLevel: "free",
    estimatedDurationMinutes: 75,
    bestTimeOfDay: "morning",
    indoorOutdoor: "outdoor",
    visited: false,
    favorite: false,
    isFree: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: [],
    createdAt: TS - 3 * DAY,
    updatedAt: TS - 3 * DAY,
  },
  {
    id: "tp-harajuku",
    title: "Takeshita Street, Harajuku",
    notes: "Peak weirdness on weekends. Try the rainbow cotton candy. Adjacent Omotesando for high-end shopping.",
    tags: ["shopping", "quirky", "street"],
    sourceType: "manual",
    city: "Tokyo",
    country: "Japan",
    neighborhood: "Harajuku",
    latitude: 35.6703,
    longitude: 139.7025,
    category: "street",
    priority: 3,
    priceLevel: "moderate",
    estimatedDurationMinutes: 60,
    bestTimeOfDay: "afternoon",
    indoorOutdoor: "outdoor",
    visited: false,
    favorite: false,
    isFree: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-tokyo",
    collectionIds: [],
    createdAt: TS - 3 * DAY,
    updatedAt: TS - 3 * DAY,
  },
];

export const DEMO_COLLECTIONS_TOKYO: Collection[] = [
  {
    id: "demo-col-tokyo-must",
    tripId: "demo-tokyo",
    name: "Must See",
    emoji: "⭐",
    color: "#c8582f",
    placeIds: ["tp-sensoji", "tp-shibuya"],
    createdAt: TS - 6 * DAY,
    updatedAt: TS - 6 * DAY,
  },
  {
    id: "demo-col-tokyo-food",
    tripId: "demo-tokyo",
    name: "Food Crawl",
    emoji: "🍜",
    color: "#648c50",
    placeIds: ["tp-tsukiji", "tp-ichiran"],
    createdAt: TS - 5 * DAY,
    updatedAt: TS - 5 * DAY,
  },
];

// ── DEMO TRIP 2: Lisbon ──────────────────────────────────────

export const DEMO_TRIP_LISBON: Trip = {
  id: "demo-lisbon",
  name: "Lisbon Weekend",
  description: "A long weekend in Portugal's most charming city. Pastéis, fado, and tile-covered hills.",
  emoji: "🇵🇹",
  startDate: "2025-05-23",
  endDate: "2025-05-25",
  timezone: "Europe/Lisbon",
  budgetStyle: "budget",
  notes: "Get a Viva Viagem metro card. Trams are unreliable but tram 28 is iconic.",
  archived: false,
  itineraryMode: "slow",
  itinerary: [
    {
      date: "2025-05-23",
      dayNumber: 1,
      theme: "Belém classics",
      notes: "Easy arrival day anchored around pastries and monuments.",
      items: [
        { id: "demo-it-lisbon-1-1", placeId: "lp-belem", startTime: "09:30", endTime: "10:15", duration: 45, locked: true, travelTimeFromPrevious: 0, order: 0 },
        { id: "demo-it-lisbon-1-2", placeId: "lp-jeronimos", startTime: "10:30", endTime: "12:00", duration: 90, locked: false, travelTimeFromPrevious: 5, order: 1 },
      ],
    },
    {
      date: "2025-05-24",
      dayNumber: 2,
      theme: "Alfama evening",
      notes: "Slow hill day with fado saved as the evening anchor.",
      items: [
        { id: "demo-it-lisbon-2-1", placeId: "lp-alfama", startTime: "14:00", endTime: "16:00", duration: 120, locked: false, travelTimeFromPrevious: 0, order: 0 },
        { id: "demo-it-lisbon-2-2", placeId: "lp-fado", startTime: "20:00", endTime: "22:00", duration: 120, locked: true, travelTimeFromPrevious: 12, order: 1 },
      ],
    },
  ],
  currency: "EUR",
  createdAt: TS - 3 * DAY,
  updatedAt: TS,
};

export const DEMO_PLACES_LISBON: Place[] = [
  {
    id: "lp-belem",
    title: "Pastéis de Belém",
    notes: "The ORIGINAL pastel de nata since 1837. Sprinkle cinnamon. Arrive early — lines are long by 10am.",
    tags: ["food", "must-eat", "historic", "morning"],
    sourceType: "manual",
    city: "Lisbon",
    country: "Portugal",
    neighborhood: "Belém",
    latitude: 38.6973,
    longitude: -9.2033,
    category: "cafe",
    priority: 1,
    priceLevel: "budget",
    estimatedDurationMinutes: 45,
    bestTimeOfDay: "morning",
    indoorOutdoor: "indoor",
    visited: false,
    favorite: true,
    isFree: false,
    dietaryTags: ["vegetarian"],
    images: [],
    tripId: "demo-lisbon",
    collectionIds: ["demo-col-lisbon-food"],
    createdAt: TS - 2 * DAY,
    updatedAt: TS - 2 * DAY,
  },
  {
    id: "lp-jeronimos",
    title: "Jerónimos Monastery",
    notes: "UNESCO heritage. Free entry on Sundays before 2pm! Otherwise €10. Allow 1.5h.",
    tags: ["architecture", "historic", "UNESCO", "free-sunday"],
    sourceType: "manual",
    city: "Lisbon",
    country: "Portugal",
    neighborhood: "Belém",
    latitude: 38.6979,
    longitude: -9.2059,
    category: "religious",
    priority: 1,
    priceLevel: "budget",
    estimatedDurationMinutes: 90,
    bestTimeOfDay: "morning",
    indoorOutdoor: "both",
    visited: false,
    favorite: true,
    isFree: false,
    isChildFriendly: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-lisbon",
    collectionIds: [],
    createdAt: TS - 2 * DAY,
    updatedAt: TS - 2 * DAY,
  },
  {
    id: "lp-alfama",
    title: "Alfama Neighbourhood Walk",
    notes: "Get lost in the narrow streets. Look for azulejo tiles. Miradouro da Graça for sunset views.",
    tags: ["walking", "historic", "photography", "neighborhood"],
    sourceType: "manual",
    city: "Lisbon",
    country: "Portugal",
    neighborhood: "Alfama",
    latitude: 38.7143,
    longitude: -9.1279,
    category: "street",
    priority: 1,
    priceLevel: "free",
    estimatedDurationMinutes: 150,
    bestTimeOfDay: "afternoon",
    indoorOutdoor: "outdoor",
    visited: false,
    favorite: true,
    isFree: true,
    isSoloFriendly: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-lisbon",
    collectionIds: [],
    createdAt: TS - 1 * DAY,
    updatedAt: TS - 1 * DAY,
  },
  {
    id: "lp-lx",
    title: "LX Factory",
    notes: "Hip creative market in a repurposed factory. Sunday market is excellent. Great restaurants inside.",
    tags: ["market", "food", "art", "weekend"],
    sourceType: "manual",
    city: "Lisbon",
    country: "Portugal",
    neighborhood: "Alcântara",
    latitude: 38.7051,
    longitude: -9.1764,
    category: "market",
    priority: 2,
    priceLevel: "moderate",
    estimatedDurationMinutes: 120,
    bestTimeOfDay: "afternoon",
    indoorOutdoor: "both",
    visited: false,
    favorite: false,
    isFree: true,
    dietaryTags: ["vegetarian", "vegan"],
    images: [],
    tripId: "demo-lisbon",
    collectionIds: ["demo-col-lisbon-food"],
    createdAt: TS - 1 * DAY,
    updatedAt: TS - 1 * DAY,
  },
  {
    id: "lp-fado",
    title: "Fado show in Mouraria",
    notes: "The birthplace of fado. Avoid tourist trap places — try A Baiuca for authentic local atmosphere.",
    tags: ["music", "culture", "evening", "fado"],
    sourceType: "manual",
    city: "Lisbon",
    country: "Portugal",
    neighborhood: "Mouraria",
    latitude: 38.7160,
    longitude: -9.1337,
    category: "entertainment",
    priority: 2,
    priceLevel: "moderate",
    estimatedDurationMinutes: 120,
    bestTimeOfDay: "evening",
    indoorOutdoor: "indoor",
    visited: false,
    favorite: false,
    isFree: false,
    isDateNight: true,
    dietaryTags: [],
    images: [],
    tripId: "demo-lisbon",
    collectionIds: [],
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: "lp-time-out",
    title: "Time Out Market",
    notes: "35+ restaurant stalls. Best food hall in Europe. Go hungry. Try the bifanas.",
    tags: ["food", "indoor", "market"],
    sourceType: "manual",
    city: "Lisbon",
    country: "Portugal",
    neighborhood: "Cais do Sodré",
    latitude: 38.7055,
    longitude: -9.1462,
    category: "market",
    priority: 2,
    priceLevel: "moderate",
    estimatedDurationMinutes: 90,
    bestTimeOfDay: "afternoon",
    indoorOutdoor: "indoor",
    visited: false,
    favorite: false,
    isFree: true,
    dietaryTags: ["vegetarian", "vegan", "seafood"],
    images: [],
    tripId: "demo-lisbon",
    collectionIds: ["demo-col-lisbon-food"],
    createdAt: TS,
    updatedAt: TS,
  },
];

export const DEMO_COLLECTIONS_LISBON: Collection[] = [
  {
    id: "demo-col-lisbon-food",
    tripId: "demo-lisbon",
    name: "Must Eat",
    emoji: "🥐",
    color: "#c8582f",
    placeIds: ["lp-belem", "lp-lx", "lp-time-out"],
    createdAt: TS - 2 * DAY,
    updatedAt: TS,
  },
];

export const DEMO_PACKING_ITEMS: PackingItem[] = [
  { id: "pk-1", tripId: "demo-tokyo", category: "Documents", name: "Passport", quantity: 1, packed: true },
  { id: "pk-2", tripId: "demo-tokyo", category: "Documents", name: "Travel insurance printout", quantity: 1, packed: false },
  { id: "pk-3", tripId: "demo-tokyo", category: "Tech", name: "Pocket WiFi / SIM card", quantity: 1, packed: false },
  { id: "pk-4", tripId: "demo-tokyo", category: "Tech", name: "Universal power adapter", quantity: 1, packed: true },
  { id: "pk-5", tripId: "demo-tokyo", category: "Clothing", name: "Comfortable walking shoes", quantity: 1, packed: false },
  { id: "pk-6", tripId: "demo-tokyo", category: "Clothing", name: "Light rain jacket", quantity: 1, packed: false },
];

// ── Seed function ────────────────────────────────────────────

export async function seedDemoData(): Promise<void> {
  const { db } = await import("./db");

  const exists = await db.trips.get("demo-tokyo");
  if (exists) return; // already seeded

  await db.transaction("rw", [db.trips, db.places, db.collections, db.packingItems], async () => {
    await db.trips.bulkPut([DEMO_TRIP_TOKYO, DEMO_TRIP_LISBON]);
    await db.places.bulkPut([...DEMO_PLACES_TOKYO, ...DEMO_PLACES_LISBON]);
    await db.collections.bulkPut([...DEMO_COLLECTIONS_TOKYO, ...DEMO_COLLECTIONS_LISBON]);
    await db.packingItems.bulkPut(DEMO_PACKING_ITEMS);
  });
}

export async function resetDemoData(): Promise<void> {
  const { db } = await import("./db");
  const demoTripIds = ["demo-tokyo", "demo-lisbon"];

  await db.transaction("rw", [db.trips, db.places, db.collections, db.packingItems], async () => {
    await Promise.all(demoTripIds.map((tripId) => db.trips.delete(tripId)));
    await Promise.all(demoTripIds.map((tripId) => db.places.where("tripId").equals(tripId).delete()));
    await Promise.all(demoTripIds.map((tripId) => db.collections.where("tripId").equals(tripId).delete()));
    await Promise.all(demoTripIds.map((tripId) => db.packingItems.where("tripId").equals(tripId).delete()));

    await db.trips.bulkPut([DEMO_TRIP_TOKYO, DEMO_TRIP_LISBON]);
    await db.places.bulkPut([...DEMO_PLACES_TOKYO, ...DEMO_PLACES_LISBON]);
    await db.collections.bulkPut([...DEMO_COLLECTIONS_TOKYO, ...DEMO_COLLECTIONS_LISBON]);
    await db.packingItems.bulkPut(DEMO_PACKING_ITEMS);
  });
}
